basePath: /
definitions:
  models.Club:
    properties:
      category:
        example: Sports
        type: string
      created_at:
        example: "2025-02-08T16:13:44Z"
        type: string
      deleted_at:
        example: "null"
        type: string
      description:
        example: A club for chess enthusiasts
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Chess Club
        type: string
      rating:
        example: 4.5
        type: number
      updated_at:
        example: "2025-02-08T16:13:44Z"
        type: string
    type: object
  models.ClubListResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Club'
        type: array
      message:
        example: Clubs retrieved successfully
        type: string
      status:
        example: success
        type: string
    type: object
  models.ClubResponse:
    properties:
      data:
        $ref: '#/definitions/models.Club'
      message:
        example: Club created successfully
        type: string
      status:
        example: success
        type: string
    type: object
  models.ErrorResponse:
    properties:
      message:
        example: Error message
        type: string
      status:
        example: error
        type: string
    type: object
  models.Response:
    properties:
      data: {}
      message:
        example: Operation successful
        type: string
      status:
        example: success
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server for Club Rank.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Club Rank API
  version: "1.0"
paths:
  /api/clubs:
    get:
      consumes:
      - application/json
      description: Get list of all clubs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ClubListResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all clubs
      tags:
      - clubs
    post:
      consumes:
      - application/json
      description: Create a new club with the provided information
      parameters:
      - description: Club object
        in: body
        name: club
        required: true
        schema:
          $ref: '#/definitions/models.Club'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.ClubResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Create a new club
      tags:
      - clubs
  /clubs:
    get:
      consumes:
      - application/json
      description: Get list of all clubs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Club'
            type: array
      summary: Get club list
      tags:
      - clubs
  /clubs/{id}:
    delete:
      description: Delete a club
      parameters:
      - description: Club ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Delete a club
      tags:
      - clubs
    get:
      description: Get a club by ID
      parameters:
      - description: Club ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Club'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get a club by ID
      tags:
      - clubs
    put:
      consumes:
      - application/json
      description: Update a club
      parameters:
      - description: Club ID
        in: path
        name: id
        required: true
        type: integer
      - description: Club
        in: body
        name: club
        required: true
        schema:
          $ref: '#/definitions/models.Club'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Club'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Update a club
      tags:
      - clubs
swagger: "2.0"
